- hosts: localhost
  sudo: yes

  tasks:

    - yum: name={{ item }} state=present
      with_items:
        - fedmsg-hub
        - rpm-ostree-toolbox
        - fedmsg-atomic-composer

    - file: path=/srv/fedora-atomic/output
            owner=root group=root mode=655 state=directory

    - file: path=/srv/fedora-atomic/{{ item }}/tasks/treecompose
            owner=root group=root mode=655 state=directory
      with_items:
        - rawhide
        - f21

    - file: path=/srv/inbox
            owner=root group=root mode=655 state=directory

    - git: repo=https://git.fedorahosted.org/git/fedora-atomic.git
           dest=/srv/fedora-atomic/rawhide/fedora-atomic

    - git: repo=https://git.fedorahosted.org/git/fedora-atomic.git
           dest=/srv/fedora-atomic/f21/fedora-atomic
           branch=f21

    - service: name=atomic-compose-rawhide state=running

    - service: name=fedmsg-hub state=running
