- hosts: localhost
  sudo: yes

  tasks:

    - user: name=rpmostreecompose
            shell=/bin/bash
            groups=systemd-journal
            generate_ssh_key=yes
      register: user

    - authorized_key: user={{ user['name'] }}
                      key="{{ user['ssh_public_key'] }}"

    - yum: name={{ item }} state=present
      with_items:
        - fedmsg-hub
        - fedmsg-relay
        - rpm-ostree-toolbox
        - ostree
        #- fedmsg-atomic-composer

    - file: path=/srv/fedora-atomic/output
            owner=rpmostreecompose group=rpmostreecompose mode=755 state=directory

    - file: path=/srv/fedora-atomic/output/{{ item }}/
            owner=rpmostreecompose group=rpmostreecompose mode=755 state=directory
      with_items:
        - rawhide
        - f21

    - file: path=/srv/fedora-atomic/{{ item }}/tasks/treecompose
            owner=rpmostreecompose group=rpmostreecompose mode=755 state=directory
      with_items:
        - rawhide
        - f21

    - file: path=/srv/inbox/{{ item }}
            owner=rpmostreecompose group=rpmostreecompose mode=755 state=directory
      with_items:
        - rawhide
        - f21

    - git: repo=https://git.fedorahosted.org/git/fedora-atomic.git
           dest=/srv/fedora-atomic/rawhide/fedora-atomic
           update=no

    - git: repo=https://git.fedorahosted.org/git/fedora-atomic.git
           dest=/srv/fedora-atomic/f21/fedora-atomic
           version=f21
           update=no

    - command: systemctl daemon-reload

    - service: name=atomic-compose-{{ item }} enabled=yes state=restarted
      with_items:
        - rawhide
        - f21

    - service: name=fedmsg-atomic-composer enabled=yes state=restarted

    - service: name=fedmsg-relay enabled=yes state=started

    - command: /usr/bin/ostree init --repo=/srv/fedora-atomic/output/{{ item }}/repo --mode=archive-z2
      sudo: yes
      sudo_user: rpmostreecompose
      args:
        creates: /srv/fedora-atomic/output/{{ item }}/repo
      with_items:
       - rawhide
       - f21

    - file: src=/srv/fedora-atomic/output/{{ item }}/repo
            dest=/srv/fedora-atomic/{{ item }}/repo
            owner=rpmostreecompose group=rpmostreecompose state=link
      with_items:
       - rawhide
       - f21
