- hosts: localhost
  sudo: yes

  tasks:
    - yum: name={{ item }} state=present
      with_items:
        - fedmsg-relay
        - fedmsg-atomic-composer

    - user: name=rpmostreecompose
            shell=/bin/bash
            groups=mock
            generate_ssh_key=yes
      register: user

    - authorized_key: user={{ user['name'] }}
                      key="{{ user['ssh_public_key'] }}"

    - file: path=/srv/fedora-atomic/
            owner={{ user['name'] }} group={{ user['name'] }} mode=755 state=directory

#    - service: name=fedmsg-atomic-composer enabled=yes state=restarted
#    - service: name=fedmsg-relay enabled=yes state=started
