- hosts: localhost
  sudo: yes

  tasks:

    - yum: name={{ item }} state=present
      with_items:
        - fedmsg-hub
        - rpm-ostree-toolbox
        - ostree
        #- fedmsg-atomic-composer

    - file: path=/srv/fedora-atomic/output
            owner=root group=root mode=655 state=directory

    - file: path=/srv/fedora-atomic/{{ item }}/tasks/treecompose
            owner=root group=root mode=655 state=directory
      with_items:
        - rawhide
        - f21

    - file: path=/srv/inbox/{{ item }}
            owner=root group=root mode=655 state=directory
      with_items:
        - rawhide
        - f21

    - git: repo=https://git.fedorahosted.org/git/fedora-atomic.git
           dest=/srv/fedora-atomic/rawhide/fedora-atomic

    - git: repo=https://git.fedorahosted.org/git/fedora-atomic.git
           dest=/srv/fedora-atomic/f21/fedora-atomic
           version=f21

    - service: name=atomic-compose-{{ item }} state=running
      with_items:
        - rawhide
        - f21

    - service: name=fedmsg-hub state=running
